import Home from '../Components/Home/index.js'
import NotFound from '../Components/NotFound/index.js'
import Login from '../Components/User/Login.js'
import ProtectedRoute from '../Components/Helper/ProtectedRoute.js'
import PainelInicial from '../Components/PainelInicial/index.js'
import Clientes from '../Components/Clientes/index.js'
import Grupos from '../Components/Grupos/index.js'
import ContasReceber from '../Components/ContasReceber/index.js'
import Caixa from '../Components/Caixa/index.js'
import Pais from '../Components/Pais/index.js'
import Estado from '../Components/Estado/index.js'
import Cidade from '../Components/Cidade/index.js'
import Filial from '../Components/Filial/index.js'
import Parametro from '../Components/Parametro/index.js'
import User from '../Components/User/index.js'
import Agenda from '../Components/Agenda/index.js'
import AgendaEvento from '../Components/AgendaEvento/index.js'
import CategoriaEvento from '../Components/CategoriaEvento/index.js'
import Especialidade from '../Components/EspecialidadeProfissional/index.js'
import Profissionais from '../Components/Profissionais/index.js'
import Consulta from '../Components/Consulta/index.js'
import ConstrutorFicha from '../Components/ConstrutorFicha/index.js'
import ConstrutorFichaGrupo from '../Components/ConstrutorFichaGrupo/index.js'
import ConstrutorFichaItem from '../Components/ConstrutorFichaItem/index.js'
import Servico from '../Components/Servico/index.js'
import OrdemServico from '../Components/OrdemServico/index.js'
import ClientesFichas from '../Components/ClientesFichas/index.js'
import MovimentacoesFinanceiras from '../Components/MovimentacoesFinanceiras/index.js'
import MenuBotoes from '../Components/MenuBotoes/index.js'
import CadastrarCliente from '../Components/Clientes/Cadastrar/index.js'
import Widgets from '../Components/Widgets/index.js'
import PainelHome from '../Components/Home/Painel.js'
import CadastrarExternoSimples from '../Components/Consulta/Cadastrar/CadastrarExternoSimples.js'
import SendMessageWhatsApp from '../Components/CanaisNotificacao/WhatsApp/index.js'
import SendEmail from '../Components/CanaisNotificacao/Email/index.js'
import Configuracoes from '../Components/Configuracoes/index.js'
import ContasReceberItem from '../Components/ContasReceberItem/index.js'
import FormaPagamento from '../Components/FormaPagamento/index.js'

export {
     Home, NotFound, Login, ProtectedRoute, PainelInicial, Clientes, Grupos, ContasReceber, Caixa, Filial, Parametro, User, Pais,
     Estado, Cidade, Agenda, AgendaEvento, CategoriaEvento, Especialidade, Profissionais, Consulta, ConstrutorFicha, ConstrutorFichaGrupo,
     ConstrutorFichaItem, Servico, OrdemServico, ClientesFichas, MovimentacoesFinanceiras, MenuBotoes, CadastrarCliente, Widgets, PainelHome, CadastrarExternoSimples,
     SendMessageWhatsApp, SendEmail, Configuracoes, ContasReceberItem, FormaPagamento,
}