import Home from '../Components/Home/index.js'
import NotFound from '../Components/NotFound/index.js'
import Login from '../Components/User/Login.js'
import ProtectedRoute from '../Components/Helper/ProtectedRoute.js'
import PainelInicial from '../Components/PainelInicial/index.js'
import Clientes from '../Components/Clientes/index.js'
import Grupos from '../Components/Grupos/index.js'
import ContasReceber from '../Components/ContasReceber/index.js'
import Caixa from '../Components/Caixa/index.js'
import Pais from '../Components/Pais/index.js'
import Estado from '../Components/Estado/index.js'
import Cidade from '../Components/Cidade/index.js'
import Filial from '../Components/Filial/index.js'
import Parametro from '../Components/Parametro/index.js'
import User from '../Components/User/index.js'
import AgendaEvento from '../Components/AgendaEvento/index.js'
import CategoriaEvento from '../Components/CategoriaEvento/index.js'
import Especialidade from '../Components/EspecialidadeProfissional/index.js'
import Profissionais from '../Components/Profissionais/index.js'
import Consulta from '../Components/Consulta/index.js'
import ConstrutorFicha from '../Components/ConstrutorFicha/index.js'

export {Home, NotFound, Login, ProtectedRoute, PainelInicial,Clientes,Grupos, ContasReceber, Caixa, Filial, Parametro, User, Pais,
     Estado, Cidade, AgendaEvento, CategoriaEvento, Especialidade, Profissionais, Consulta, ConstrutorFicha}