import {
    BANDEIRA_CARTAO_ALL_POST, BANDEIRA_CARTAO_DELETE_POST, BANDEIRA_CARTAO_ONE_GET,
    BANDEIRA_CARTAO_SAVE_POST, BANDEIRA_CARTAO_UPDATE_POST
} from '../../Components/CartaoCreditoBandeira/Routes/index';

export {
    BANDEIRA_CARTAO_ALL_POST, BANDEIRA_CARTAO_DELETE_POST, BANDEIRA_CARTAO_ONE_GET,
    BANDEIRA_CARTAO_SAVE_POST, BANDEIRA_CARTAO_UPDATE_POST
};